version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: login_test
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
#     networks:
#       - my_network

volumes:
  postgres_data:

# networks:
#   my_network:

# docker compose -f segoba-postgres-db.yml up
# -f specifies the file to use; by default, it is "docker-compose.yml".
# -d runs the containers in detached mode (in the background).
